### ISSUE TITLE
no route definitions found

### ISSUE THREAD

**Issue by haidi50hk** [HiveProjectLtd/HivePoC#1]
hi, 
after succesful installation of the cloned reop i got this 
message in my browser when i go to localhost:3000 or 127.0.0.1:3000

   "iron:router"
"no route difinitions found"

To create a route:

Router.route('/', function () {
  this.render('Home', {
    data: function () { return Items.findOne({_id: this.params._id}); }
  });
});

**Comment by morpheus7CS** [comment]
Hey, the issue has been adressed in the last update. Please git pull in the latest changes & it will work.

Kind regards.

**Comment by djovan** [comment]
issue resolved by adding ABI files to repository
